spring:
  datasource:
    url: jdbc:mysql://localhost:3306/system?serverTimezone=GMT&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database: mysql
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect




#    url: jdbc:sqlserver://115.28.207.13:1433;DatabaseName=oil2
#    username: oil2
#    password: yuetu19032
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

#    url: jdbc:sqlserver://192.168.2.131:1433;DatabaseName=oil
#    username: sa
#    password: root
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

#指定模板的路径
  freemarker:
    template-loader-path: classpath:/templates/mybatis

#spring.freemarker.allow-request-override=false
#spring.freemarker.cache=true
#spring.freemarker.check-template-location=true
#spring.freemarker.charset=UTF-8
#spring.freemarker.content-type=text/html
#spring.freemarker.expose-request-attributes=false
#spring.freemarker.expose-session-attributes=false
#spring.freemarker.expose-spring-macro-helpers=false

#需要生成的codegenerte
data_resources: mybatis

# 生成源文件的绝对地址
controller: com.liaoin.smart.system.provider.controller

server: com.liaoin.smart.system.provider.service

serverImpl: com.liaoin.smart.system.provider.service.impl

mappers: com.liaoin.smart.system.provider.mapper

entity: com.liaoin.smart.bean.system
#controller: com.liaoin.smp.entity.controller
#
#server: com.liaoin.smp.entity.service
#
#serverImpl: com.liaoin.smp.entity.service.impl
#
#mappers: com.liaoin.smp.entity.dao
#
#entity: com.liaoin.smp.entity

#数据版本
version: v1

# 文件生成路径
targetProject: D:/WorkSpace/template/src/main/java/
# 包名
packageName: com.liaoin.smart.system.provider
# 指定数据库表名
TABLE_NAME: t_housing_estate_building,t_housing_estate_building_house



mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
#    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

