spring:
  datasource:
    url: jdbc:mysql://39.104.16.81:3306/liaoin_pm?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

#指定模板的路径
  freemarker:
    template-loader-path: classpath:/templates/jap

#spring.freemarker.allow-request-override=false
#spring.freemarker.cache=true
#spring.freemarker.check-template-location=true
#spring.freemarker.charset=UTF-8
#spring.freemarker.content-type=text/html
#spring.freemarker.expose-request-attributes=false
#spring.freemarker.expose-session-attributes=false
#spring.freemarker.expose-spring-macro-helpers=false

#需要生成的codegenerte
data_resources: jpa

# 生成源文件的绝对地址
controller: com.liaoin.pm.controller

server: com.liaoin.pm.user.service

serverImpl: com.liaoin.pm.user.service.impl

mappers: com.liaoin.pm.user.dao

entity: com.liaoin.pm.user.entity


# 文件生成路径
targetProject: D:/WorkSpace/template/src/main/java/
# 包名
packageName: com.liaoin.pm.user
# 指定数据库表名
TABLE_NAME: t_user_department,t_user_extattr,t_user_info,t_user_menu,t_user_orderIn_depts,t_user_roles



mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
#    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

