spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fusion?characterEncoding=utf-8&useSSL=false
    hikari:
      username:
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

#指定模板的路径
  freemarker:
    template-loader-path: classpath:/templates/jpa

#spring.freemarker.allow-request-override=false
#spring.freemarker.cache=true
#spring.freemarker.check-template-location=true
#spring.freemarker.charset=UTF-8
#spring.freemarker.content-type=text/html
#spring.freemarker.expose-request-attributes=false
#spring.freemarker.expose-session-attributes=false
#spring.freemarker.expose-spring-macro-helpers=false

#需要生成的codegenerte
data_resources: jpa

# 生成源文件的绝对地址
controller: com.liaoin.microservice.provlder.backstage.controller

server: com.liaoin.microservice.provlder.backstage.service

serverImpl: com.liaoin.microservice.provlder.backstage.service.impl

mappers: com.liaoin.microservice.dao.backstage

entity: com.liaoin.microservice.bean.entity.backstage


# 文件生成路径
targetProject: D:/WorkSpace/template/src/main/java/
# 包名
packageName: com.liaoin.microservice
# 指定数据库表名
TABLE_NAME: m_cadre_rewards,m_cadre_train



mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
#    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

